AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template to create an S3 bucket for Lambda deployment.

Resources:
  COEAWSOBSS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "coe-aws-obs-deployment-${AWS::Region}-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    DeletionPolicy: Delete # Delete the bucket when the stack is deleted

Outputs:
  LambdaDeploymentBucketName:
    Value: !Ref COEAWSOBSS3Bucket
    Export:
      Name: lambda-deployment-bucket-name